# Generated by Django 2.0 on 2019-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Decline'), (3, 'In progress'), (4, 'Complete')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.IntegerField(verbose_name='Product ID'),
        ),
    ]
