# Generated by Django 2.0 on 2019-07-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190713_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
